Add installation step to add the bundle in the config
zenstruck/messenger-test pull request #85
Opened 2024-07-11 09:52 UTC by dazz

I ran into an error and it was fixed by adding the bundle.

![image](https://github.com/zenstruck/messenger-test/assets/182954/036e90fb-a424-4b4a-b726-9bee1ca99b6d)

This might not happen to newer projects with recipes enabled.

2024-07-24 14:10 UTC, kbond requested changes
Thanks @dazz, let's just add a note to make it clear this step may not be required.

I am curious why it didn't auto-add for you. No flex in your project?

2024-07-24 14:10 UTC, kbond commented on README.md
> +2. Add the bundle in `config/bundles.php`:
```suggestion
2. If not added automatically by Symfony Flex, add the bundle in `config/bundles.php`:
```

2024-08-05 19:48 UTC, dazz commented
> Thanks @dazz, let's just add a note to make it clear this step may not be required.
> 
> I am curious why it didn't auto-add for you. No flex in your project?

Hey @kbond, yes it's a rather old project which gets updates, but is never fresh set up so it's missing some features, like Symfony Flex.

2024-08-06 07:59 UTC, nikophil approved these changes

2024-08-06 08:00 UTC, merged

2024-08-06 08:00 UTC, nikophil commented
thanks @dazz