Reset TestTransport on ensureKernelShutdown
zenstruck/messenger-test pull request #90
Opened 2024-09-12 07:07 UTC by HypeMC

An alternative approach to #82, requires https://github.com/symfony/symfony/pull/58240

2024-09-13 14:18 UTC, nikophil requested changes
Hi @HypeMC 

thanks for this PR :)

> requires https://github.com/symfony/symfony/pull/58240

why don't we implement `ResetInterface`? So we won't need Symfony 7.2 to benefit from this feature.


Would you mind adding a test which confirms that everything is working? We should test this in both a test which uses `InteractsWithMessenger` trait, and a test which doesn't, I guess

2024-09-13 14:18 UTC, nikophil commented on src/InteractsWithMessenger.php
> +    #[After]
I'm wondering if this will work, because `KernelTestCase::ensureKernelShutdown()` is called on `TestCase::tearDown()`

but IIRC the order of the hooks in PHPUnit is the following:
- `#[Before]` hooks
- `setUp()` method in the test case
- // run test...
- `tearDown()` method in test case
- `#[After]` hooks

so I think the kernel will be shutdown too soon. 

but since PHPUnit 11.3, [priority for hook methods](https://github.com/sebastianbergmann/phpunit/pull/5890) has been introduced. 

I think we can leverage this feature and add `#[After(priority: 10)]`. Sadly, this would only work since PHPUnit 11.3

WDYT?

2024-09-13 14:56 UTC, HypeMC commented
> > requires [symfony/symfony#58240](https://github.com/symfony/symfony/pull/58240)
> 
> why don't we implement `ResetInterface`? So we won't need Symfony 7.2 to benefit from this feature.

@nikophil Hi, the reason is [your comment about introducing a BC break](https://github.com/zenstruck/messenger-test/pull/82#issuecomment-2096198752). With this approach, the existing method's behavior remains unchanged.
 
> Would you mind adding a test which confirms that everything is working? We should test this in both a test which uses `InteractsWithMessenger` trait, and a test which doesn't, I guess

Sure, no problem, but I don't think I can actually cover the [original scenario](https://github.com/zenstruck/messenger-test/pull/77#issuecomment-2014827406) as it depends on the execution order and a specific test being run first:

> So if we have this scenario :
> 
> 1. Test1 add messages on transport but doesn't care about messenger assertions so doesn't implement InteractsWithMessenger
> 2. messages remains in transports
> 3. Test2 implements InteractsWithMessenger and should reset collected messages before tests.

2024-09-13 14:58 UTC, HypeMC commented on src/InteractsWithMessenger.php
> +    #[After]
@nikophil The order shouldn't be relevant here. This only enable the auto-reset on kernel shutdown for the **next** test.

2024-09-13 15:27 UTC, nikophil commented on src/InteractsWithMessenger.php
> +    #[After]
sorry, but I don't understand :sweat_smile: 

Given that original scenario:
1. Test1 add messages on transport but doesn't care about messenger assertions so doesn't implement `InteractsWithMessenger`
2. messages remains in transports
3. Test2 implements `InteractsWithMessenger` and should reset collected messages before tests.

kernel shutdown would be called at the end of `1` and `3`, right? so if we auto-reset on kernel shutdown, we'll reset at the end of `3` which would not fix the problem?

2024-09-13 15:43 UTC, nikophil commented on src/InteractsWithMessenger.php
> +    #[After]
ok, now I understand more clearly what's going on, and indeed, this will fix the problem, very clever :)

2024-09-13 15:48 UTC, nikophil commented
> the reason is https://github.com/zenstruck/messenger-test/pull/82#issuecomment-2096198752. With this approach, the existing method's behavior remains unchanged.

oups yes, you're right :hand_over_mouth:  let's do your way then!

> Also, https://github.com/symfony/symfony/pull/58240 is a bugfix, so it won't require 7.2.

perfect

> depends on the execution order and a specific test being run first

yeah... we're doing strange things to test behavior between tests in this library :sweat_smile: ... basically, not using `--order-by` nor any `executionOrder ` in the xml will play the tests in the natural order (alphabetically). I know this is not ideal, but the only way to test such behaviors. No problem if you don't want to bother with this, I might do it at some point. Maybe I'll upgrade first to PHPUnit 10, in order to leverage `#[DependsExternal]` attribute...

2024-09-13 15:48 UTC, nikophil approved these changes

2024-09-13 15:51 UTC, HypeMC commented
> > depends on the execution order and a specific test being run first
> 
> yeah... we're doing strange things to test behavior between tests in this library 😅 ... basically, not using `--order-by` nor any `executionOrder ` in the xml will play the tests in the natural order (alphabetically). I know this is not ideal, but it is the only way to test such behaviors. No problem if you don't want to bother with this, I might do it at some point. Maybe I'll upgrade first to PHPUnit 10, in order to leverage `#[DependsExternal]` attribute...

@nikophil Actually, I just noticed the `testsuite name="zenstruck/messenger-test transports are reset correctly"` which is exactly what I need, so I think the test i possible.

2024-09-13 16:20 UTC, HypeMC commented
@nikophil Funny thing, the test was kind of already there, it just didn't work when all tests were run cause it requires `TestTransport::$enableMessagesCollection` to be set to its initial value of `true` for the bug to manifest. The tests are now failing cause they require https://github.com/symfony/symfony/pull/58240. See https://github.com/zenstruck/messenger-test/pull/90/commits/ab2123d74dbb586b92c6bfb35095deea08c44eea

2024-09-13 16:25 UTC, nikophil commented
Don't hesitate to ping me once the fix is released in SF, and I'll merge and release this PR

It seems there is a bunch of issues and PR that can be closed as well. Thanks!

2024-09-21 14:22 UTC, HypeMC commented
@nikophil The fix has been released by Symfony, however, I don't think it's possible to get the tests for 6.3 and 7.0 to pass since those versions are no longer supported. I'm not sure what to do about this, the fix is valid for all supported versions.

2024-09-26 07:11 UTC, nikophil commented
hey @HypeMC 

I just discovered that [some tests are failing](https://github.com/zenstruck/messenger-test/pull/92), maybe because of a new version of Symfony. I'll fix them asap, before merging your PR

2024-09-26 16:42 UTC, nikophil commented
@HypeMC would you mind to rebase your PR?

2024-09-26 17:15 UTC, HypeMC commented
> @HypeMC would you mind to rebase your PR?

@nikophil Done

2024-09-26 17:23 UTC, nikophil approved these changes

2024-09-26 17:23 UTC, merged

2024-09-26 17:33 UTC, nikophil commented
released in 1.10.0